[project]
name = "pytrees-rs"
version = "1.0.0"
dependencies = [
"scikit-learn",
]

[project.urls]
"Homepage" = "https://github.com/haroldks/pytrees-rs"


[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
