[book]
authors = ["Harold Kiossou"]
language = "en"
src = "src"
title = "pytrees-rs"
description = "Optimal and lookahead decision trees in Rust, with a scikit-learn API."

[output.html]
git-repository-url = "https://github.com/haroldks/pytrees-rs"
