[package]
name = "contree-cli"
description = "Command line driver for the contree optimal decision tree search."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "con-tree"
path = "src/main.rs"

[dependencies]
contree.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true

[lints]
workspace = true
