[package]
name = "dtrees-rs"
description = "Optimal (DL8.5) and greedy (LGDT) decision trees over binary features."
version = "1.0.3"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
clap.workspace = true
float-cmp.workspace = true
rustc-hash.workspace = true
search_trail.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
paste.workspace = true

[lints]
workspace = true
